### ISSUE TITLE
s.HostInfos() crash

### ISSUE THREAD

**Issue by baiyuxiong** [akhenakh/statgo#6]
````
gomail(30652,0xb0310000) malloc: *** error for object 0x48095d0: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
SIGABRT: abort
PC=0x7fff8c8aa286 m=7
signal arrived during cgo execution

goroutine 22 [syscall, locked to thread]:
runtime.cgocall(0x4002b40, 0xc820199898, 0x0)
	/usr/local/go/src/runtime/cgocall.go:120 +0x11b fp=0xc820199868 sp=0xc820199838
github.com/akhenakh/statgo._Cfunc_sg_free_stats_buf(0x4809628, 0xc800000000)
	??:0 +0x35 fp=0xc820199898 sp=0xc820199868
github.com/akhenakh/statgo.(*Stat).HostInfos(0xc82000b4c0, 0x1)
	/Users/baiyuxiong/go/src/github.com/akhenakh/statgo/host_info.go:45 +0x22b fp=0xc820199920 sp=0xc820199898
github.com/baiyuxiong/gomail/status.HostInfos(0x0, 0x0)
	/Users/baiyuxiong/go/src/github.com/baiyuxiong/gomail/status/state.go:15 +0x2f fp=0xc820199958 sp=0xc820199920
github.com/baiyuxiong/gomail/http.configRoutes.func2(0x4d00108, 0xc8201f49a0, 0xc8200e7880)
	/Users/baiyuxiong/go/src/github.com/baiyuxiong/gomail/http/routes.go:126 +0x348 fp=0xc820199b58 sp=0xc820199958
net/http.HandlerFunc.ServeHTTP(0x451a170, 0x4d00108, 0xc8201f49a0, 0xc8200e7880)
	/usr/local/go/src/net/http/server.go:1422 +0x3a fp=0xc820199b78 sp=0xc820199b58
net/http.(*ServeMux).ServeHTTP(0xc820014870, 0x4d00108, 0xc8201f49a0, 0xc8200e7880)
	/usr/local/go/src/net/http/server.go:1699 +0x17d fp=0xc820199bd0 sp=0xc820199b78
net/http.serverHandler.ServeHTTP(0xc820132000, 0x4d00108, 0xc8201f49a0, 0xc8200e7880)
	/usr/local/go/src/net/http/server.go:1862 +0x19e fp=0xc820199c30 sp=0xc820199bd0
net/http.(*conn).serve(0xc820150420)
	/usr/local/go/src/net/http/server.go:1361 +0xbee fp=0xc820199f88 sp=0xc820199c30
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc820199f90 sp=0xc820199f88
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:1910 +0x3f6

````

**Comment by akhenakh** [comment]
thanks for the report I can reproduce, will provide a fix soon
